---
- name: Install
  ansible.builtin.shell:
    cmd: curl https://mise.run | {{ ansible_facts['env']['SHELL'] }}
    creates: "{{ ansible_facts['env']['HOME'] }}/.local/bin/mise"

- name: Configure
  ansible.builtin.template:
    src: config.toml.j2
    dest: "{{ ansible_facts['env']['HOME'] }}/.config/mise/config.toml"

- name: Initialize
  ansible.builtin.shell:
    chdir: "{{ ansible_facts['env']['HOME'] }}/.config/mise"
    cmd: mise install
