---
- name: Install
  ansible.builtin.shell:
    cmd: curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh | bash
    creates: "{% if ansible_facts['os_family'] == 'Darwin' %}/opt/homebrew{% else %}/home/linuxbrew/.linuxbrew{% endif %}"
