---
- name: Install apt packages
  become: true
  ansible.builtin.apt:
    name:
      - zsh

- name: Install Zinit
  ansible.builtin.shell:
    cmd: curl -fsSL https://raw.githubusercontent.com/zdharma-continuum/zinit/HEAD/scripts/install.sh | bash
    creates: "{{ ansible_facts['env']['HOME'] }}/.local/share/zinit/zinit.git"

- name: Configure Zinit
  ansible.builtin.blockinfile:
    path: "{{ ansible_facts['env']['HOME'] }}/.zshrc"
    marker: "# {mark} ANSIBLE MANAGED BLOCK FOR ZINIT"
    prepend_newline: true
    append_newline: true
    block: |
      zinit ice compile'(pure|async).zsh' pick'async.zsh' src'pure.zsh'
      zinit light sindresorhus/pure
