---
- name: Install apt packages
  become: true
  ansible.builtin.apt:
    name:
      - zsh
  when: ansible_facts['os_family'] != "Darwin"

- name: Install Zinit
  ansible.builtin.shell:
    cmd: curl -fsSL https://raw.githubusercontent.com/zdharma-continuum/zinit/HEAD/scripts/install.sh | bash
    creates: "{{ ansible_env.HOME }}/.local/share/zinit/zinit.git"

- name: Configure Zinit
  ansible.builtin.blockinfile:
    path: "{{ ansible_env.HOME }}/.zshrc"
    marker: "# {mark} ANSIBLE MANAGED BLOCK FOR ZINIT"
    prepend_newline: true
    append_newline: true
    block: |
      ZSH_THEME="bureau"
      zinit snippet OMZL::git.zsh
      zinit snippet OMZP::git
      zinit cdclear -q
      zinit snippet OMZP::golang
      zinit snippet OMZP::helm
      zinit snippet OMZP::k9s
      zinit snippet OMZP::kubectl
      zinit snippet OMZP::kubectx
      zinit snippet OMZP::node
      zinit snippet OMZP::npm
      zinit snippet OMZP::ssh
      zinit snippet OMZP::vscode
      zinit snippet OMZP::yarn
      zinit snippet OMZL::clipboard.zsh
      zinit snippet OMZL::nvm.zsh
      zinit snippet OMZT::$ZSH_THEME
