---
- name: Install apt packages
  become: true
  ansible.builtin.apt:
    name:
      - git
      - dkms

- name: Tmp checkout dir
  ansible.builtin.tempfile:
    state: directory
  register: _checkout

- name: Clone
  ansible.builtin.git:
    repo: https://github.com/medusalix/xone.git
    dest: "{{ _checkout.path }}"
    version: master

- name: Install
  become: true
  ansible.builtin.shell:
    chdir: "{{ _checkout.path }}"
    cmd: ./install.sh

- name: Get firmware
  become: true
  ansible.builtin.shell:
    chdir: "{{ _checkout.path }}"
    cmd: ./xone-get-firmware.sh
