---
- name: Download
  ansible.builtin.shell:
    cmd: curl -fsSL https://github.com/containerd/nerdctl/releases/download/v2.1.4/nerdctl-2.1.4-linux-amd64.tar.gz | tar -xzf- -C {{ ansible_env.HOME }}/.local
    creates: "{{ ansible_env.HOME }}/.local/bin/nerdctl"

- name: Rootlesskit apparmor
  become: true
  ansible.builtin.template:
    src: rootlesskit-apparmor
    dest: "/etc/apparmor.d/{{ ansible_env.HOME | regex_replace('^/', '') | replace('/', '.') }}..local.bin.rootlesskit"
    mode: "0644"

- name: Install containerd
  ansible.builtin.shell:
    cmd: containerd-rootless-setuptool.sh install
    creates: "{{ ansible_env.HOME }}/.config/systemd/user/containerd.service"

- name: Install buidlkit
  ansible.builtin.shell:
    cmd: containerd-rootless-setuptool.sh install-buildkit
    creates: "{{ ansible_env.HOME }}/.config/systemd/user/buildkit.service"

- name: Symlink docker
  ansible.builtin.file:
    src: "{{ ansible_env.HOME }}/.local/bin/nerdctl"
    dest: "{{ ansible_env.HOME }}/.local/bin/docker"
    state: link
