---
# - name: Install ollama
#   become: true
#   ansible.builtin.shell:
#     cmd: curl -fsSL https://ollama.com/install.sh | sh
#     creates: /usr/local/bin/ollama

# - name: Pull qwen3:8b
#   ansible.builtin.shell:
#     cmd: ollama pull qwen3:8b

- name: Prepare Copilot API systemd directory
  ansible.builtin.file:
    path: "{{ ansible_facts['env']['HOME'] }}/.config/systemd/user"
    state: directory
    mode: "0755"

- name: Configure Copilot API
  vars:
    github_token: "{{ lookup('ansible.builtin.env', 'GITHUB_TOKEN') }}"
  ansible.builtin.template:
    src: copilot-api.service.j2
    dest: "{{ ansible_facts['env']['HOME'] }}/.config/systemd/user/copilot-api.service"
    mode: "0644"
  notify: systemd service copilot-api restart

- name: Prepare Claude config directory
  ansible.builtin.file:
    path: "{{ ansible_facts['env']['HOME'] }}/.claude"
    state: directory
    mode: "0755"

- name: Configure Claude
  ansible.builtin.template:
    src: claude-settings.json.j2
    dest: "{{ ansible_facts['env']['HOME'] }}/.claude/settings.json"
    mode: "0644"

- name: Configure RTK
  ansible.builtin.command:
    cmd: rtk init --global --auto-patch --hook-only
